---
# tasks file for nginx-php-fpm
- name: Apt update
  apt:
    update_cache: yes

- name: install packages
  apt:
    name: "{{ pkgs }}"
    state: latest
  vars:
    pkgs:
      - php-fpm
      - nginx
  
